version: '3.7'

services:
  db:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_DB: wedding
      POSTGRES_USER: wedding
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./volume.local/db_data:/var/lib/postgresql